# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{guppy}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Scott Barron"]
  s.date = %q{2009-10-29}
  s.description = %q{foo}
  s.email = %q{scott@elitists.net}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "doc/jamis.rb",
     "guppy.gemspec",
     "lib/garmin.rb",
     "lib/garmin/activity.rb",
     "lib/garmin/db.rb",
     "lib/garmin/gpx_parser.rb",
     "lib/garmin/lap.rb",
     "lib/garmin/tcx_parser.rb",
     "lib/garmin/track_point.rb",
     "test/fixtures/example.tcx",
     "test/helper.rb",
     "test/test_activity.rb",
     "test/test_db.rb",
     "test/test_garmin.rb",
     "test/test_gpx_parser.rb",
     "test/test_lap.rb",
     "test/test_tcx_parser.rb",
     "test/test_track_point.rb"
  ]
  s.homepage = %q{http://github.com/rubyist/guppy}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Ruby library for parsing tcx and gpx files}
  s.test_files = [
    "test/helper.rb",
     "test/test_activity.rb",
     "test/test_db.rb",
     "test/test_garmin.rb",
     "test/test_gpx_parser.rb",
     "test/test_lap.rb",
     "test/test_tcx_parser.rb",
     "test/test_track_point.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

